# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      job_env1: je111

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo 'JOB_ENV1:$JOB_ENV1'
    - name: set env
      id: set-env
      env: 
        env1: e111
      run: |
        echo "job_env1:$job_env1"
        echo "::set-env name=env2::e222"
        echo "::set-output name=out1::o111"
    - name: get env
      id: get-env
      run: |
        echo "job_env1:$job_env1"
        echo "env2:$env2"
        echo "get output out1:${{ steps.set-env.outputs.out1 }}"
    - name: get env2
      shell: pwsh
      run: |
        echo "job_env1:$job_env1"
        echo "env2:$env2"
        echo "get output out1:${{ steps.set-env.outputs.out1 }}"
